services:
  fleetshare-1-client:
    image: techroy23/docker-fleetshare:latest
    container_name: fleetshare-1-client
    pull_policy: always
    restart: always
    privileged: true
    environment:
      - TOKEN=abcdef12-3456-7890-abcd-ef1234567890
    volumes:
      - ./proxy.txt:/app/proxy.txt
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"

  fleetshare-watchtower:
    image: containrrr/watchtower
    container_name: fleetshare-watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --cleanup
      - --include-stopped
      - --include-restarting
      - --revive-stopped
      - --interval
      - "60"
      - fleetshare-1-client
